/**
 * Typed error hierarchy for the policy module, mirroring the pattern
 * `lib/identity/errors.ts`, `lib/credentials/errors.ts`, and
 * `lib/trust/errors.ts` established: one distinct class per failure
 * mode, never a bare `throw new Error("...")`.
 *
 * These three are thrown ONLY by `validate.ts`'s `validatePolicy`, when
 * the DATA describing a policy is itself broken — a category error,
 * different from `Explanation`'s `refusalKind` (which describes a
 * REQUEST being refused under a policy that is itself perfectly valid).
 * `evaluatePolicyRequest` never swallows one of these into a refusal —
 * a malformed policy is a configuration bug, not a counterparty being
 * denied, and conflating the two would let a broken policy silently
 * read as "every request just happens to be refused" instead of loudly
 * failing to load at all. See `engine.ts`'s module comment.
 */

export type PolicyDefinitionFailureKind = "malformed" | "contradiction" | "unknown-rule-type";

/** The policy value (or one of its rules) does not have the shape this
 *  module requires — missing/wrong-typed field, empty required string,
 *  a `RevocationRequirement` missing its justification fields, etc.
 *  Covers "malformed/empty policy" from the M5 brief: a bare `{}`, a
 *  missing `rules` array, or any other structurally broken input all
 *  land here rather than throwing an unhandled `TypeError` from deep
 *  inside validation. */
export class PolicyMalformedError extends Error {
  override readonly name = "PolicyMalformedError";
  readonly kind: PolicyDefinitionFailureKind = "malformed";

  constructor(readonly reason: string) {
    super(`Policy malformed: ${reason}`);
  }
}

/** Two rules within one policy make a request's outcome genuinely
 *  ambiguous — e.g. two `action-scope` rules both governing the same
 *  action with no ordering rule between them. Never silently resolved
 *  by "first match wins" or "last match wins": an ambiguity a human
 *  autor almost certainly didn't intend is exactly the kind of mistake
 *  this module refuses to guess its way past. */
export class PolicyContradictionError extends Error {
  override readonly name = "PolicyContradictionError";
  readonly kind: PolicyDefinitionFailureKind = "contradiction";

  constructor(readonly reason: string) {
    super(`Policy contradicts itself: ${reason}`);
  }
}

/** A rule's `kind` discriminant is not one of the kinds this module
 *  understands (`ACTION_SCOPE_RULE_KIND` / `HISTORY_NARROW_RULE_KIND`).
 *  A policy is DATA — it can arrive from a JSON config file written by
 *  a human or generated by a future tool, so an unrecognised rule kind
 *  is a real, expected failure mode to guard, not merely a type-system
 *  concern the compiler already rules out for hand-written TypeScript
 *  policies. */
export class PolicyUnknownRuleTypeError extends Error {
  override readonly name = "PolicyUnknownRuleTypeError";
  readonly kind: PolicyDefinitionFailureKind = "unknown-rule-type";

  constructor(readonly ruleKind: unknown) {
    super(`Unknown policy rule kind: ${JSON.stringify(ruleKind)}`);
  }
}

/** Grouping type for anything a caller might want to `instanceof`-check
 *  across the whole "why didn't this policy even load" space. */
export type PolicyDefinitionError = PolicyMalformedError | PolicyContradictionError | PolicyUnknownRuleTypeError;
