/**
 * Runtime validation of a `Policy` value — the boundary every policy
 * must cross before `engine.ts` ever evaluates a request against it.
 *
 * ## Why this exists even though `Policy` is already a TypeScript type
 *
 * A `Policy` is meant to be authored as DATA (see `policy-types.ts`'s
 * module comment) — plausibly loaded from a JSON file, generated by a
 * future authoring tool, or received over `app/`'s API boundary (M8).
 * None of those paths go through TypeScript's type checker at the point
 * the bytes actually arrive; a `JSON.parse(...) as Policy` cast makes
 * the compiler stop complaining without making the data any safer. This
 * is the exact same lesson M3/M4 already applied to credentials (a type
 * annotation on a JWT payload proves nothing about what's actually in
 * the bytes) and M5's own task brief applies to history claims
 * ("claims arrive as JSON, not TypeScript") — applied here to the
 * POLICY itself, which is just as much untrusted input as a credential
 * when it crosses a real boundary.
 *
 * Every failure mode throws one of `errors.ts`'s three typed errors —
 * never a bare `TypeError`/`RangeError` from indexing into
 * unexpected-shaped input, and never a silent "just skip this bad rule
 * and keep going" that could leave a policy quietly more permissive
 * than its author intended.
 */
import { PolicyContradictionError, PolicyMalformedError, PolicyUnknownRuleTypeError } from "./errors.js";
import {
  ACTION_SCOPE_RULE_KIND,
  HISTORY_NARROW_RULE_KIND,
  type ActionScopeRule,
  type ComparisonOperator,
  type HistoryNarrowRule,
  type Policy,
  type PolicyRule,
  type RevocationRequirement,
} from "./policy-types.js";

const COMPARISON_OPERATORS: ReadonlySet<ComparisonOperator> = new Set(["lte", "lt", "gte", "gt", "eq"]);

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function requireNonEmptyString(value: unknown, path: string): string {
  if (!isNonEmptyString(value)) {
    throw new PolicyMalformedError(`"${path}" must be a non-empty string`);
  }
  return value;
}

function requireFiniteNumber(value: unknown, path: string): number {
  if (!isFiniteNumber(value)) {
    throw new PolicyMalformedError(`"${path}" must be a finite number`);
  }
  return value;
}

function validateNumericRecord(value: unknown, path: string): Record<string, number> {
  if (!isPlainObject(value)) {
    throw new PolicyMalformedError(`"${path}" must be an object of field -> number`);
  }
  const out: Record<string, number> = {};
  for (const [key, entry] of Object.entries(value)) {
    out[key] = requireFiniteNumber(entry, `${path}.${key}`);
  }
  return out;
}

function validateActionScopeRule(raw: Record<string, unknown>, path: string): ActionScopeRule {
  return {
    kind: ACTION_SCOPE_RULE_KIND,
    id: requireNonEmptyString(raw["id"], `${path}.id`),
    description: requireNonEmptyString(raw["description"], `${path}.description`),
    action: requireNonEmptyString(raw["action"], `${path}.action`),
    maxScope: validateNumericRecord(raw["maxScope"], `${path}.maxScope`),
  };
}

function validateHistoryNarrowRule(raw: Record<string, unknown>, path: string): HistoryNarrowRule {
  const operator = raw["operator"];
  if (typeof operator !== "string" || !COMPARISON_OPERATORS.has(operator as ComparisonOperator)) {
    throw new PolicyMalformedError(`"${path}.operator" must be one of ${[...COMPARISON_OPERATORS].join(", ")}, got ${JSON.stringify(operator)}`);
  }
  return {
    kind: HISTORY_NARROW_RULE_KIND,
    id: requireNonEmptyString(raw["id"], `${path}.id`),
    description: requireNonEmptyString(raw["description"], `${path}.description`),
    action: requireNonEmptyString(raw["action"], `${path}.action`),
    observationType: requireNonEmptyString(raw["observationType"], `${path}.observationType`),
    metric: requireNonEmptyString(raw["metric"], `${path}.metric`),
    operator: operator as ComparisonOperator,
    threshold: requireFiniteNumber(raw["threshold"], `${path}.threshold`),
    scopeField: requireNonEmptyString(raw["scopeField"], `${path}.scopeField`),
    narrowedMax: requireFiniteNumber(raw["narrowedMax"], `${path}.narrowedMax`),
  };
}

function validateRule(raw: unknown, index: number): PolicyRule {
  const path = `rules[${index}]`;
  if (!isPlainObject(raw)) {
    throw new PolicyMalformedError(`"${path}" must be an object`);
  }
  const kind = raw["kind"];
  if (kind === ACTION_SCOPE_RULE_KIND) {
    return validateActionScopeRule(raw, path);
  }
  if (kind === HISTORY_NARROW_RULE_KIND) {
    return validateHistoryNarrowRule(raw, path);
  }
  // Deliberately thrown as its OWN error kind, not folded into
  // PolicyMalformedError: "the shape is broken" and "the shape is fine
  // but names a kind this module has never heard of" are different
  // failure modes a caller (or a future migration script upgrading
  // policies to a new rule kind) may want to tell apart.
  throw new PolicyUnknownRuleTypeError(kind);
}

/**
 * `RevocationRequirement` gets its own validator — see
 * `policy-types.ts`'s doc comment on why this field is required, not
 * optional, and why its permissive branch cannot be a bare boolean: this
 * function is exactly where "omission fails closed" and "the permissive
 * choice must be justified" are enforced for any policy that didn't
 * arrive through TypeScript's own type checker.
 */
function validateRevocationHandling(raw: unknown, path: string): RevocationRequirement {
  if (!isPlainObject(raw)) {
    throw new PolicyMalformedError(`"${path}" is required and must be an object naming how unchecked revocation is handled (see RevocationRequirement)`);
  }
  const requireChecked = raw["requireChecked"];
  if (requireChecked === true) {
    return { requireChecked: true };
  }
  if (requireChecked === false) {
    return {
      requireChecked: false,
      acknowledgedBy: requireNonEmptyString(raw["acknowledgedBy"], `${path}.acknowledgedBy`),
      reason: requireNonEmptyString(raw["reason"], `${path}.reason`),
    };
  }
  throw new PolicyMalformedError(`"${path}.requireChecked" must be a literal boolean (true, or false with acknowledgedBy/reason) — got ${JSON.stringify(requireChecked)}`);
}

/**
 * Validate an untrusted value as a `Policy`, throwing a typed
 * `PolicyDefinitionError` for every way it can be broken:
 *   - malformed shape (missing/wrong-typed fields, empty policy object,
 *     a missing `revocationHandling`) -> `PolicyMalformedError`
 *   - an unrecognised rule `kind` -> `PolicyUnknownRuleTypeError`
 *   - two `action-scope` rules governing the same action ->
 *     `PolicyContradictionError`
 *
 * A policy with a `rules: []` array (and otherwise valid `id`/`version`/
 * `revocationHandling`) is deliberately NOT treated as malformed: it is
 * a legitimate, if extreme, "deny everything" policy (see `engine.ts`'s
 * `"no-matching-rule"` refusal) — fail-closed already falls out of
 * having no rule ever match, with no special case needed. What IS
 * rejected here is a policy whose top-level SHAPE is broken (not an
 * object at all, or missing a required field) — that is the "empty
 * policy" the M5 brief means by "malformed/empty policy... -> typed
 * error, never unhandled, never silent permit": e.g. `{}` fails on the
 * missing `id`, not on having zero rules.
 */
export function validatePolicy(input: unknown): Policy {
  if (!isPlainObject(input)) {
    throw new PolicyMalformedError("policy must be a JSON object");
  }

  const id = requireNonEmptyString(input["id"], "id");
  const version = requireNonEmptyString(input["version"], "version");

  const rulesRaw = input["rules"];
  if (!Array.isArray(rulesRaw)) {
    throw new PolicyMalformedError('"rules" must be an array');
  }

  const rules: PolicyRule[] = [];
  const actionScopeRuleIdByAction = new Map<string, string>();
  for (let index = 0; index < rulesRaw.length; index++) {
    const rule = validateRule(rulesRaw[index], index);
    if (rule.kind === ACTION_SCOPE_RULE_KIND) {
      const existingRuleId = actionScopeRuleIdByAction.get(rule.action);
      if (existingRuleId !== undefined) {
        throw new PolicyContradictionError(
          `two "action-scope" rules ("${existingRuleId}" and "${rule.id}") both govern action "${rule.action}" — ambiguous which ceiling applies`,
        );
      }
      actionScopeRuleIdByAction.set(rule.action, rule.id);
    }
    rules.push(rule);
  }

  const revocationHandling = validateRevocationHandling(input["revocationHandling"], "revocationHandling");

  return { id, version, rules, revocationHandling };
}
